version: '3.8'

services:
    php:
        build: &server
            context: .
            dockerfile: docker/php/Dockerfile
            target: php-dev
        container_name: eventsauce_demo_php
        volumes: &server-volumes
            - .:/usr/share/nginx/html:rw,cached
        depends_on:
            - mysql
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
            target: nginx-dev
        container_name: eventsauce_demo_nginx
        volumes: *server-volumes
        depends_on:
            - php
        ports:
            - ${HTTP_PORT}:80

    mysql:
        image: mysql:8.0
        container_name: eventsauce_demo_mysql
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - ${DB_PORT}:3306

    rabbit:
        build:
            context: .
            dockerfile: docker/rabbit/Dockerfile
        container_name: eventsauce_demo_rabbit
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBIT_PSWD}
        ports:
            - "15672:15672"
            - ${RABBIT_PORT}:5672

    messenger:
        build: *server
        container_name: eventsauce_demo_messenger
        command:
            - "./bin/console"
            - "messenger:consume"
            - "high_priority"
            - "normal_priority"
            - "--time-limit=3600"
        restart: unless-stopped
        depends_on:
            - php
        volumes: *server-volumes

    message_outbox:
        build: *server
        container_name: eventsauce_demo_outbox
        command:
            - "./bin/console"
            - "andreo:eventsauce:message-outbox:consume"
            - "cart_aggregate_relay"
            - "order_aggregate_relay"
            - "event_dispatcher_relay"
            - "--sleep=2"
        restart: unless-stopped
        volumes: *server-volumes
        depends_on:
            - php

